[project]
name = "p1204_3"
version = "0.1.4"
description = "ITU-T P.1204.3 reference implementation"
readme = "README.md"
authors = [
    { name = "Steve Göring", email = "steve.goering@tu-ilmenau.de" },
    { name = "Ramachandra Rao Rakesh Rao", email = "Rakesh-Rao.Ramachandra-Rao@tu-ilmenau.de" },
    { name = "Werner Robitza", email = "werner.robitza@gmail.com" },
]
license-files = ["LICENSE.md"]
requires-python = ">=3.9"
dependencies = [
    "numpy>=1.24.4",
    "pandas>=2.0.3",
    "scikit-learn>=1.2.2",
    "scipy>=1.10.1",
]

[project.scripts]
p1204_3 = "p1204_3:main"

[dependency-groups]
dev = [
    "black>=24",
    "gitchangelog>=3.0.4",
    "pytest>=8.3",
]

[build-system]
requires = ["hatchling>=1.27"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
exclude = ["p1204_3/bitstream_mode3_videoparser", "test_videos"]

[tool.hatch.build.targets.wheel]
packages = ["p1204_3"]
exclude = ["p1204_3/bitstream_mode3_videoparser"]
